

server:
  port: 8083

spring:
  application:
    name: dubbo-provider

dubbo:
  application:
    name: dubbo-provider
  registry:
    address: zookeeper://39.105.12.20:8999 # 使用zookeeper注册中心暴露服务地址
  protocol:
    name: dubbo # dubbo的RPC协议
    port: 20881 # dubbo的RPC端口
  monitor:
    protocol: registry




