

server:
  port: 8082

spring:
  application:
    name: dubbo-provider

dubbo:
  application:
    name: dubbo-provider
  registry:
    address: zookeeper://39.105.12.20:8999 # 使用zookeeper注册中心暴露服务地址
  protocol:
    name: dubbo # dubbo的RPC协议
    port: 20880 # dubbo的RPC端口
  monitor:
    protocol: registry
  provider:
    filter: providerFilter

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId}] [%thread] %-5level %logger{50} - %msg%n'




