

server:
  port: 8082

spring:
  application:
    name: dubbo-provider
  dubbo:
    application:
      name: dubbo-provider
    registry:
      address: zookeeper://39.105.12.20:8999
    protocol:
      name: dubbo
      port: 20880
    scan: com.github.dge1992.dubboprovider


